config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('users.urls', namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import SigninView, SignupView, ClientListView, VerifySuccessView  # , ClientCreateView,

# mailing,
app_name = MailingConfig.name

urlpatterns = [
    # path('', mailing, name='login'),

    # path('', SigninView.as_view(template_name='mailing/login.html'), name='login'),#'template_name=mailing/Client1.html'
    # path('client_register', SignupView.as_view(), name='register'),
    path('login_success', SignupView.as_view(template_name='mailing/login.html'), name='login_success'),
    path('register_success', VerifySuccessView.as_view(template_name='mailing/Client_list.html'), name='register_success'),

    # path('client_logout', LogoutView.as_view(), name='logout'),



    # path('client_register', ClientListView.as_view(), name='register'),
    path('Client_list/', ClientListView.as_view(template_name='mailing/Client_list.html'), name='Client_list')

# Client_list/<int:pk>
]
# urlpatterns = [path('', SigninView.as_view(template_name='spa/login.html'), name='login'),
#                path('register', SignupView.as_view(template_name='spa/register.html'), name='register'),
#                path('home/', SignupView.as_view(template_name='spa/home.html'), name='home')

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from rest_framework import serializers, viewsets, routers

# from rest_framework.authtoken.admin import User
from django.contrib.auth.models import User
from rest_framework.routers import DefaultRouter

from users.apps import UsersConfig
from users.views import UserLoginView, SignupView, change_status, Habit_listAPIView, Habit_createAPIView, \
    Habit_updateAPIView, Habit_deleteAPIView

app_name = UsersConfig.name

router = DefaultRouter()
# router = routers.DefaultRouter()
# router.register(r'users', Habit_listAPICreateView)
router.register(r'habit_list', Habit_listAPIView.as_view(),
                basename='habit_list')  # template_name='users/habit_list.html'

urlpatterns = [
    # path('', mailing, name='login'),

    path('', UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', SignupView.as_view(), name='register'),

    path('logout/', LogoutView.as_view(), name='logout'),

    # path('register/', CustomRegisterView.as_view(template_name='users/register.html'), name='register'),
    path('habit_list/', Habit_listAPIView.as_view(), name='habit_list'),
    path('habit_create/', Habit_createAPIView.as_view(), name='habit_create'),
    path('habit_update/', Habit_updateAPIView.as_view(), name='habit_update'),
    path('habit_delete/', Habit_deleteAPIView.as_view(), name='habit_delete'),
    path('status/<int:pk>/', change_status, name='status'),

]

base/models.py
NULLABLE = {'blank': True,  'null': True}

mailing/models.py
import django
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from users.models import User, CustomUserManager

NULLABLE = {'blank': True, 'null': True}



class Mailinglog(models.Model):
    mailing = models.CharField(max_length=100, verbose_name='Email')
    result = models.CharField(max_length=100, verbose_name='Result')
    last_attempt = models.DateTimeField(auto_now=True)




# class Emails(models.Model):#################ForeignKey  Client###########Hochu ostavit EmailField i FK
#     email = models.EmailField(max_length=50, verbose_name='Email')######

# Class StatusMssg(models.Model):
#     is_active = models.BooleanField(default=True)################ForeignKey  Mssg##############

# class Settings(models.Model):


    # status = models.CharField(max_length=10, choices=STATUSES, default=STATUS_CREATED)
    # time = models.TimeField()###Ne ponimau zachem time

base/forms.py
from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

mailing/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField, AuthenticationForm





from django import forms

from users.models import User


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

class SigninForm(StyleFormMixin, AuthenticationForm):
    pass
class SignupForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ("email",)
#         field_classes = {"username": UsernameField}
#
# class ClientForm(forms.ModelForm):
#     class Meta:
#         model = Client
#         fields = '__all__'

base/views.py
from django.shortcuts import render

# Create your views here.

mailing/views.py
import time
from django.conf import settings
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.core.management import BaseCommand
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView, CreateView, ListView, UpdateView, TemplateView

from mailing.forms import ClientForm, SignupForm, SigninForm



# class SigninView(LoginView):
#     template_name = 'mailing/login.html'
#     form_class = SigninForm


# class SignupView(CreateView):
#     template_name = 'mailing/register.html'
#     model = Client
#     form_class = SignupForm
#     success_url = reverse_lazy('mailing:Client_list')

    # def form_valid(self, form):
    #     if form.is_valid():
    #         self.object = form.save()
    #         set_verify_token_and_send_mail(self.object)
    #     return super().form_valid(form)
# class VerifySuccessView(TemplateView):
#     success_url = reverse_lazy('mailing:Client_list')
#     template_name = 'mailing/register.html'

# class ClientListView(ListView):
#     model = Client
#     form_class = ClientForm
#     success_url = reverse_lazy('mailing:Mssg_list')
#     template_name = 'mailing/Client_list.html'



# class ClientCreateView(CreateView):#Zapretili sozdanie producta
#     model = Client
#     # permission_required = 'catalog.create_Product'
#     #form_class = SubjectForm
#     form_class = ClientForm
#     # fields = ('product_name', 'product_description', 'preview', 'price_per_unit', 'category')
#     success_url = reverse_lazy('mailing:Client_list')
#     template_name = 'mailing/Client_list.html'
#
#
# class ClientUpdateView(UpdateView):#LoginRequiredMixin,
#     model = Client
#     # form_class = ClientForm
#     # success_url = reverse_lazy('catalog:Product_list')
#     template_name = 'mailing/Client_list.html'

#
# class ClientDeleteView(DeleteView):#UserPassesTestMixin,
#     model = Client
#     form_class = ClientForm
#     success_url = reverse_lazy('catalog:Product_list')
#     template_name = 'catalog/product_confirm_delete.html'
#
#     # def test_func(self):
#     #     return self.request.user.is_superuser
#
#
# class ClientDetailView(DetailView):#LoginRequiredMixin,
#     model = Client
#     # form_class = ProductForm
#     success_url = reverse_lazy('catalog:Product_list')
#     template_name = 'catalog/Product_detail.html'
#######################Primer sozdania formi dlia zapolnenia polya
# from django import forms
# from django.shortcuts import get_object_or_404
#
# class ItemForm(forms.ModelForm):
#     class Meta:
#         model = Item
#         fields = ("name", )
#
# def bound_form(request, id):
#     item = get_object_or_404(Item, id=id)
#     form = ItemForm(instance=item)
#     return render_to_response('bounded_form.html', {'form': form})

mailing/templates/mailing/Client1.html
        <div class="float-end">
            {% if user.is_authenticated %}
            {{Client.comment_set.count}}
                <a class="btn btn-link" href="{% url 'mailing:login' %}"> Профиль </a>
                <a href="{% url 'mailing:login' %}"> Выход </a>
            {% else %}
                <a href="{% url 'mailing:login' %}"> Вход </a>
            {% endif %}
        </div>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mailing:Client_list' %}">Clients list</a>
        </li>

{%  load static %}
 <table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
            <tr>

                <th scope="col">название курса</th>
                <th scope="col">описание курса</th>
                <th scope="col">фото курса</th>
                <th scope="col">название урока</th>
                <th scope="col">описание урока</th>
                <th scope="col">фото урока</th>
            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>


                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>
                    <td>{{object.product_description}}</td>
                    <td>{{object.category}}</td>
                    <td>{{object.price_per_unit}}</td>

                    <td>{{object.get_status_display}

                                <a class="btn btn-light" href="#">X</a>

                                <a class="btn btn-light" href="#">V</a>

                    </td>
                    <td>
                        <a class="btn.btn-default" href="#" >Update</a>

                            <a class="btn.btn-default" href="#" >Create</a>


                            <a class="btn.btn-default" href="#" >Delete</a>


                    </td>

                    </td>
                </tr>

          {% endfor %}

          </tbody>
        </table>




<title>Mailing Service</title>

 <form method="post">
        {% csrf_token %}
        {{form_as_p}}
     <p>
        <input name="topic" placeholder="topic" />
    </p>
     <p>
       <textarea name="message" placeholder="text"></textarea>
    </p>
     <p>
          <input type="submit" value="vvod">

     </p>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>


     <input type="text" value="This is some text" id="text" style="width: 150px;" />
<br />
<input type="button" value="Click Me" id="button" />

     <html>
    <head>
        <meta charset="utf-8">
        <title>Текстовые поля в HTML5</title>
    </head>
    <body>
        <form>
            <p><input type="text" name="Client.name" placeholder="Введите имя" size="18" maxlength="11" /></p>
            <p>
                <button type="submit">Отправить</button>
                <button type="reset">Отмена</button>
            </p>
        </form>
    </body>
</html>

mailing/templates/mailing/Client_list.html
<table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
            <tr>

                <th scope="col">название курса</th>
                <th scope="col">описание курса</th>
                <th scope="col">фото курса</th>
                <th scope="col">название урока</th>
                <th scope="col">описание урока</th>
                <th scope="col">фото урока</th>
            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>


                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>
                    <td>{{object.product_description}}</td>
                    <td>{{object.category}}</td>
                    <td>{{object.price_per_unit}}</td>

                    <td>{{object.get_status_display}

                                <a class="btn btn-light" href="#">X</a>

                                <a class="btn btn-light" href="#">V</a>

                    </td>
                    <td>
                        <a class="btn.btn-default" href="#" >Update</a>

                            <a class="btn.btn-default" href="#" >Create</a>


                            <a class="btn.btn-default" href="#" >Delete</a>


                    </td>

                    </td>
                </tr>

          {% endfor %}

          </tbody>
        </table>

mailing/templates/mailing/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>UserCustom authenticate</title>
</head>
    <body class="container">
<ul     class="list-group">
        <li class="list-group-item">
            CustomUser: {{ mailing.User }}
        </li>
        <li class="list-group-item">
            <a href="{% url 'mailing:login' %}">Home</a>
        </li>
</ul>
    {% block content %}
    {% endblock %}
    </body>

</body>
</html>

mailing/templates/mailing/index.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> Project fm Mazo </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'catalog:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'catalog:Category_List' %}">Category List</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:Product_list' %}">Product List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:contacts' %}">Contact us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:Rec_list' %}">Records list</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:create' %}">Records add form</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:Product_create' %}">Products create form</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
        {% else %}
           <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
        {% endif %}


      </ul>
    </div>
  </div>
</nav>

mailing/templates/mailing/index2.html
<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalToggleLabel">Modal 1</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Show a second modal and hide this one with the button below.
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal">Open second modal</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalToggleLabel2">Modal 2</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Hide this modal and show the first with the button below.
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Back to first</button>
      </div>
    </div>
  </div>
</div>
<button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal

mailing/templates/mailing/login.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h1 class="h3 mb-3 fw-normal">Авторизуйтесь</h1>
        {{ form.as_p }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">Вход</button>

        <br>
        <a class="btn btn-link" href="{% url 'mailing:register' %}">Нет аккаунта?</a>
    </form>
{% endblock %}

mailing/templates/mailing/main_menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> Project fm Mazo </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'catalog:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'catalog:Category_List' %}">Category List</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:Product_list' %}">Product List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:contacts' %}">Contact us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:Rec_list' %}">Records list</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:create' %}">Records add form</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:Product_create' %}">Products create form</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
        {% else %}
           <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
        {% endif %}


      </ul>
    </div>
  </div>
</nav>

mailing/templates/mailing/register.html
{% extends 'users/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Зарегистрируйтесь</h1>
        {{ form.as_p }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">Регистрация</button>
        <a class="btn btn-link" href="{% url 'mailing:login' %}">Есть аккаунт?</a>
    </form>

{% endblock %}