config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('users.urls', namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from rest_framework import serializers, viewsets, routers

# from rest_framework.authtoken.admin import User
from django.contrib.auth.models import User
from rest_framework.routers import DefaultRouter

from users.apps import UsersConfig
from users.views import UserLoginView, SignupView, change_status, Habit_listAPIView, Habit_createAPIView, \
    Habit_updateAPIView, Habit_deleteAPIView

app_name = UsersConfig.name

router = DefaultRouter()
# router = routers.DefaultRouter()
# router.register(r'users', Habit_listAPICreateView)
router.register(r'habit_list', Habit_listAPIView.as_view(),
                basename='habit_list')  # template_name='users/habit_list.html'

urlpatterns = [
    # path('', mailing, name='login'),

    path('', UserLoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', SignupView.as_view(), name='register'),

    path('logout/', LogoutView.as_view(), name='logout'),

    # path('register/', CustomRegisterView.as_view(template_name='users/register.html'), name='register'),
    path('habit_list/', Habit_listAPIView.as_view(), name='habit_list'),
    path('habit_create/', Habit_createAPIView.as_view(), name='habit_create'),
    path('habit_update/', Habit_updateAPIView.as_view(), name='habit_update'),
    path('habit_delete/', Habit_deleteAPIView.as_view(), name='habit_delete'),
    path('status/<int:pk>/', change_status, name='status'),

]

base/models.py
NULLABLE = {'blank': True,  'null': True}

users/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.contrib.auth.hashers import make_password
NULLABLE = {'blank': True, 'null': True}

class CustomUserManager(UserManager):

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)

    # use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user


class User(AbstractUser):
    objects = CustomUserManager()


    username = None
    email = models.EmailField(
        verbose_name="Почта",
        max_length=54,
        unique=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватарка', blank=True, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
class Habit(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.CharField(max_length=150, verbose_name='место', **NULLABLE)
    time_todo = models.TimeField(auto_now_add=True, verbose_name='время, когда необходимо выполнять привычку')##Изменяется при изменении модели
    action = models.CharField(max_length=150, verbose_name='действие, которое представляет из себя привычка')
    useful = models.BooleanField(**NULLABLE, verbose_name='полезная привычка или нет', default=True)

    if_pleasant = models.ForeignKey('users.Habit', **NULLABLE, on_delete=models.CASCADE, related_name='canbewith_useful', verbose_name='привычка, которую можно привязать к выполнению полезной привычки')

    # def filter_clients(self, instance): Nikak ne vvesti globalnoe ogranichenie
    #     query_set = Habit.objects.all().filter(id=self.client_id)
    #     print("------------------------", instance)
    #     return query_set
    if_connected = models.ForeignKey('self', **NULLABLE, on_delete=models.CASCADE, related_name='mustbewith_useful', verbose_name='привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных')
    period = models.CharField(max_length=100, verbose_name='периодичность выполнения привычки для напоминания в днях', **NULLABLE)
    prize = models.CharField(max_length=150, verbose_name='чем пользователь должен себя вознаградить после выполнения', **NULLABLE)
    time_fulfil = models.IntegerField(verbose_name='время, которое предположительно потратит пользователь на выполнение привычки', **NULLABLE)
    is_published = models.BooleanField(**NULLABLE, verbose_name='привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки', default=False)

    def __str__(self):
        return f'{self.action}'# related to: {self.client}'
    # class Meta:users_user_groups
    #     permissions = [
    #         ("set_is_published", "Can publish habit"),
    #         # ("add_habit", "Can add habit"),
    #         # ("delete_habit", "Can delete habit"),
    #     ]

base/forms.py
from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from base.forms import StyleFormMixin
from users.models import User

class UserSigninForm(StyleFormMixin, AuthenticationForm):
    pass


class UserSignupForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ("email",)
         # field_classes = {"username": UsernameField}

class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ("email",)

base/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.contrib.auth.views import LoginView
from django.http import HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from rest_framework import generics
from rest_framework.mixins import CreateModelMixin, UpdateModelMixin, DestroyModelMixin

from mailing.forms import SigninForm, SignupForm
from users.forms import UserRegisterForm
from users.models import User, Habit
from users.seriaizers import HabitSerializer


class UserLoginView(LoginView):
    model = User
    # form_class = UserCustomCreationForm
    success_url = reverse_lazy('users:habit_list')
    template_name = 'users/login.html'


class SignupView(CreateView):
    template_name = 'users/register.html'
    model = User
    form_class = SignupForm
    success_url = reverse_lazy('users:habit_list')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
        return super().form_valid(form)


# class CustomRegisterView(CreateView):
#     model = User
#     form_class = UserRegisterForm
#
#     def form_valid(self, form):
#         if form.is_valid():
#             self.object = form.save()
#
#             # if form.data.get('need_generate', False):
#             #     self.object.set_password(
#             #         self.object.make_random_password(length=12)
#             #     )
#             #     self.object.save()
#             self.object.is_active = False
#             # send_register_mail()
#             self.object.save()
#         return super().form_valid(form)

class Habit_listAPIView(generics.ListAPIView):
    serializer_class = HabitSerializer
    queryset = Habit.objects.all()
    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_active:
            return queryset.filter(client=self.request.user) ## Kazhdii mozhet smotret tolko svoi privichki
        return queryset

class Habit_createAPIView(generics.CreateAPIView, CreateModelMixin):
    serializer_class = HabitSerializer
    queryset = Habit.objects.all()

#     permission_classes = (RulesCreateLesson,)
class Habit_updateAPIView(generics.UpdateAPIView, UpdateModelMixin):
    serializer_class = HabitSerializer
    queryset = Habit.objects.all()

class Habit_deleteAPIView(generics.DestroyAPIView, DestroyModelMixin):
    serializer_class = HabitSerializer
    queryset = Habit.objects.all()

def change_status(request, pk):##Kogda detail ili delete budem ispolzovat
    if request.user.has_perm('catalog.set_is_published'):

    # product_item = Product.objects.filter(pk=pk).first()
    # if product_item:
    #     if ... is None:
        habit_item = get_object_or_404(Habit, pk=pk)
        if habit_item.is_published:
            habit_item.published_status = True
        else:
            habit_item.published_status = True
        habit_item.save()
        return redirect(reverse('users:habit_list'))

    raise HttpResponseBadRequest

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Signin Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        html,
        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

</head>
<body class="text-center">

<main class="form-signin w-100 m-auto">
    <h1>Habits</h1>
    {% block content %}
    {% endblock %}
    <p class="mt-5 mb-3 text-muted">&copy; 2023–{% now 'Y' %}</p>
</main>


</body>
</html>

users/templates/users/habit_form.html
{%extends 'users/base.html'%}
  {% block content %}
<H3>Creating habit in progress<H3>
    <div class="row">
      <div class="col-4">
        <div class="card">
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{form.as_p}}
                  <button class="btn btn-outline-secondary" type="submit" id="input-group-text">Button</button>

            </form>
        </div>
      </div>
    </div>
      {% endblock %}
    </div>

users/templates/users/habit_list.html
{% extends 'users/base.html' %}
{% block content %}

<table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
            <tr>

                <th scope="col">привычка клиента №</th>
                <th scope="col">место привычки</th>
                <th scope="col">время привычки</th>
                <th scope="col">действие</th>
                <th scope="col">полезность</th>
                <th scope="col">может быть ссвязана с полезной</th>
                 <th scope="col">должна быть ссвязана с полезной</th>
                 <th scope="col">периодичность</th>
                <th scope="col">вознаграждение</th>
                <th scope="col">время выполнения</th>
                <th scope="col">опубликовано или нет</th>

            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>
                    <td>{{object.client}}</td>
                    <td>{{object.place}}</td>
                    <td>{{object.time_todo}}</td>
                    <td>{{object.action}}</td>
                    <td>{{object.useful}}</td>
                    <td>{{object.if_pleasant}}</td>

                    <td>{{object.if_connected}}</td>
                    <td>{{object.period}}</td>
                    <td>{{object.prize}}</td>
                    <td>{{object.time_fulfil}}</td>
                    <td>{{object.is_published}}</td>
                     <td>{{object.get_status_display}}
                        {% if perms.catalog.set_published_status %}
                            {% if object.published_status %}

                                <a class="btn btn-light" href="{% url 'users:status' object.pk %}">X</a>
                                {% else %}
                                <a class="btn btn-light" href="{% url 'users:status' object.pk %}">V</a>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn.btn-default" href="{% url 'users:habit_update' object.pk %}" >Update</a>
                        {% if perms.users.create_habit %}
                            <a class="btn.btn-default" href="{% url 'users:habit_create' object.pk %}" >Create</a>
                        {% endif %}
                        {% if perms.users.delete_habit %}
                            <a class="btn.btn-default" href="{% url 'users:habit_delete' object.pk %}" >Delete</a>
                        {% endif %}

                    </td>

                </tr>

          {% endfor %}

          </tbody>
        </table>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% block content %}
    <h1>Login</h1>
    <hr>
    {% if form.errors %}
        <p>{{ form.errors.error }}</p>
    {% endif %}
    <form action="{% url 'users:login' %}" method="post">
    {{ form }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Submit</button>
    </form>
    <a href="{% url 'users:register' %}">Нет аккаунта</a>
{% endblock %}
~

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Зарегистрируйтесь</h1>
        {{ form.as_p }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">Регистрация</button>
        <a class="btn btn-link" href="{% url 'users:login' %}">Есть аккаунт?</a>
    </form>

{% endblock %}